function GainMatSave = GainMat(in1)
%GainMat
%    GainMatSave = GainMat(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    12-Dec-2022 23:34:07

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
GainMatSave = reshape([1.0./1.0e+1,0.0,0.0,1.0./1.0e+1,0.0,0.0,3.0,1.0,conj(q1),0.0,1.0,0.0,0.0,1.0./1.0e+1,0.0,1.0./5.0,1.0,conj(q2),0.0,0.0,1.0,0.0,0.0,1.8e+1,1.0,1.0,conj(q3)],[9,3]);
