function g1 = gravity_terms(in1)
%GRAVITY_TERMS
%    G1 = GRAVITY_TERMS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    13-Dec-2022 02:42:34

q2 = in1(2,:);
q3 = in1(3,:);
et1 = cos(q2).*7.722432+sin(q2).*1.50700920289828e-17;
et2 = cos(q2).*sin(q3).*(-1.56446577138489)+cos(q3).*sin(q2).*1.56446577138489;
g1 = [0.0;et1+et2;cos(q3).*sin(q2).*(-1.56446577138489)+sin(q3).*(cos(q2)-7.498798913309288e-33).*1.56446577138489;0.0];
